# Generated by Django 5.0.7 on 2025-10-03 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_dataset_islive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DisplayName', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('VoteExpire', models.DateTimeField(blank=True, null=True)),
                ('AdminNotes', models.TextField(blank=True, null=True)),
                ('PublicView', models.BooleanField(default=False)),
                ('Active', models.BooleanField(default=True)),
                ('HighlightBefore', models.DateTimeField(blank=True, null=True)),
                ('RoundId', models.IntegerField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('DataSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='applicants.dataset')),
            ],
            options={
                'ordering': ['DisplayName'],
            },
        ),
    ]
