# Generated by Django 5.0.7 on 2025-10-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='description',
            field=models.TextField(blank=True, max_length=100000),
        ),
        migrations.AddField(
            model_name='applicant',
            name='round',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
