# Generated by Django 5.0.7 on 2025-10-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
