# Generated by Django 5.0.7 on 2025-10-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='street',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
