# Generated by Django 5.0.7 on 2025-10-11 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0009_applicant_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.batch'),
        ),
    ]
