# Generated by Django 5.0.7 on 2025-10-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('vote_cast', 'Vote Cast'), ('comment_added', 'Comment Added')], max_length=50),
        ),
    ]
