# Generated by Django 5.0.7 on 2025-10-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0014_alter_activity_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('REVIEW', 'Under Review'), ('INTERVIEW', 'Interview'), ('DECIDED', 'Decision Made')], db_index=True, default='NEW', max_length=50),
        ),
    ]
