# Generated by Django 5.0.7 on 2025-10-29 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0017_applicant_assigned_reviewers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='assigned_reviewers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'COMMITTEE_MEMBER'}, related_name='assigned_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
