# Generated by Django 5.0.7 on 2026-01-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0018_batch_assigned_reviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='flagged_for_discussion',
            field=models.BooleanField(default=False, help_text='Flag for committee discussion'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='applicant_profiles/'),
        ),
    ]
