# Generated by Django 5.0.7 on 2026-01-23 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0019_applicant_flagged_for_discussion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='flagged_for_discussion',
        ),
        migrations.AddField(
            model_name='applicant',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_applicants', to=settings.AUTH_USER_MODEL),
        ),
    ]
