# Generated by Django 5.2.10 on 2026-03-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0020_remove_applicant_flagged_for_discussion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
