# Generated by Django 5.2.10 on 2026-03-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0022_applicant_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('vote_cast', 'Vote Cast'), ('comment_added', 'Comment Added'), ('flag_added', 'Flag Added')], max_length=50),
        ),
    ]
