# Generated by Django 5.2.10 on 2026-03-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0023_alter_activity_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='source_folder',
            field=models.CharField(blank=True, default='', help_text='Top-level folder name from bulk upload', max_length=255),
        ),
    ]
