# Generated by Django 5.2.10 on 2026-03-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0024_applicant_source_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
