# Generated by Django 5.2.10 on 2026-03-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0025_alter_applicant_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='review_group',
            field=models.CharField(blank=True, choices=[('', 'Unassigned'), ('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='review_group',
            field=models.CharField(blank=True, choices=[('', 'Unassigned'), ('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C')], default='', max_length=1),
        ),
    ]
