# Generated by Django 5.2.10 on 2026-03-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0027_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
