# Generated by Django 5.2.10 on 2026-05-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0029_notificationattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='candidate_info_imported',
            field=models.BooleanField(default=False, help_text='Whether candidate info was imported from Excel'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='first_gen',
            field=models.BooleanField(default=False, verbose_name='First Generation'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='former_post_bacc',
            field=models.BooleanField(default=False, verbose_name='Former Post Bacc'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='pb_to_dmd',
            field=models.BooleanField(default=False, verbose_name='PB to DMD'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='re_applicant',
            field=models.BooleanField(default=False, verbose_name='Re-Applicant'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='three_plus_four',
            field=models.BooleanField(default=False, verbose_name='3+4'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='total_ai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total AI'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='total_nc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total NC'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='z_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Z-Score'),
        ),
    ]
