# Generated by Django 5.2.10 on 2026-05-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0030_applicant_candidate_info_imported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('REVIEW', 'Under Review'), ('INTERVIEW', 'Interview'), ('DECIDED', 'Decision Made'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], db_index=True, default='NEW', max_length=50),
        ),
    ]
