# Generated by Django 5.2.10 on 2026-05-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0032_dataset_target_class_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('vote_cast', 'Vote Cast'), ('comment_added', 'Comment Added'), ('flag_added', 'Flag Added'), ('decision_made', 'Decision Made')], max_length=50),
        ),
    ]
