# Generated by Django 5.2.10 on 2026-06-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0033_alter_activity_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='ethnicity',
        ),
    ]
