# Generated by Django 5.2.10 on 2026-06-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0034_remove_applicant_ethnicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('INTERVIEW', 'Interview'), ('INTERVIEW_COMPLETE', 'Interview Complete'), ('ACCEPTED', 'Accepted'), ('ACCEPTED_MAILED', 'Accepted – Mailed'), ('ACCEPTED_NOT_MAILED', 'Accepted – Not Mailed'), ('WAITLISTED', 'Waitlisted'), ('REJECTED', 'Rejected'), ('DECLINED', 'Candidate Declined')], db_index=True, default='INTERVIEW', max_length=50),
        ),
    ]
