# Generated by Django 5.2.10 on 2026-06-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0037_remove_dataset_dataset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='flag_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
