# Generated by Django 5.2.10 on 2026-06-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0039_remove_applicant_flag_comment_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='age',
        ),
        migrations.AddField(
            model_name='applicant',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Citizenship'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dat_academic_avg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='DAT Academic Average'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dat_biology',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='DAT Biology'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dat_general_chem',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='DAT General Chemistry'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dat_organic_chem',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='DAT Organic Chemistry'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dat_perceptual_ability',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='DAT Perceptual Ability'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dat_quantitative_reasoning',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='DAT Quantitative Reasoning'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dat_reading_comp',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='DAT Reading Comprehension'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dat_total_science',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='DAT Total Science'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dental_experience_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dental Experience Hours'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gpa_bcp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='BCP GPA'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gpa_overall',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Overall GPA'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gpa_science',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Science GPA'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='shadowing_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Shadowing Hours'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State of Residence'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='candidate_info_imported',
            field=models.BooleanField(default=False, help_text='Whether candidate info was imported from Excel or PDF'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
