# Generated by Django 5.2.10 on 2026-06-10 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0041_reviewpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='applicants.reviewpanel'),
        ),
    ]
