# Generated by Django 5.2.10 on 2026-06-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0042_batch_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='person_type',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
