# Generated by Django 5.2.10 on 2026-06-12 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0043_profile_person_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='review_group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='review_group',
        ),
        migrations.AddField(
            model_name='activity',
            name='target_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_entries', to='applicants.batch'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_reviewer',
            field=models.BooleanField(default=False, help_text='Admin users with this flag can be assigned to batches as sitting committee members and can switch to committee mode.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('vote_cast', 'Vote Cast'), ('comment_added', 'Comment Added'), ('flag_added', 'Flag Added'), ('decision_made', 'Decision Made'), ('batch_uploaded', 'Batch Uploaded')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicants.applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='assigned_reviewers',
            field=models.ManyToManyField(blank=True, related_name='assigned_applicants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batch',
            name='assigned_reviewers',
            field=models.ManyToManyField(blank=True, related_name='assigned_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
