# Generated by Django 5.2.10 on 2026-06-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0044_remove_batch_review_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previous_login',
            field=models.DateTimeField(blank=True, help_text='The login timestamp prior to the current session. Used to detect newly uploaded batches since last login.', null=True),
        ),
    ]
