# Generated by Django 5.2.10 on 2026-06-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0045_profile_previous_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confidentiality_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
