from django.urls import path
from . import views
from .views import toggle_applicant_flag

urlpatterns = [
    path("applicant/", views.applicant_list, name="applicant_list"),
    path("activity-feed/", views.activity_feed, name="activity_feed"),
    path("login/", views.email_login, name="login"),
    path("applicant/<int:pk>/", views.applicant_detail, name="applicant_detail"),
    path("applicant/new/", views.applicant_create, name="applicant_create"),
    path("applicant/batch-action/", views.batch_action, name="batch_action"),
    path("applicant/<int:pk>/vote/<str:value>/", views.vote, name="vote"),
    path("applicant/<int:pk>/add-files/", views.add_files, name="add_files"),
    path("applicant/<int:pk>/edit/", views.applicant_edit, name="applicant_edit"),
    path("applicant/compare/", views.compare_applicants, name="compare_applicants"),
    path("applicant/<int:pk>/profile/", views.applicant_profile_partial, name="applicant_profile_partial"),
    path("applicant/export/", views.export_applicants_csv, name="export_applicants_csv"),
    path("applicant/<int:pk>/update-status/", views.update_status, name="update_status"),
    path("applicant/<int:pk>/update-score/", views.update_score, name="update_score"),
    path("datasets/", views.dataset_list, name="dataset_list"),
    path("datasets/new/", views.dataset_create, name="dataset_create"),
    path("datasets/<int:pk>/", views.dataset_detail, name="dataset_detail"),
    path("datasets/<int:pk>/edit/", views.dataset_edit, name="dataset_edit"),
    path("", views.dashboard, name="dashboard"),
    path("batches/", views.batch_list, name="batch_list"),
    path("batches/new/", views.batch_create, name="batch_create"),
    path("batches/<int:pk>/", views.batch_detail, name="batch_detail"),
    path("batches/<int:pk>/edit/", views.batch_edit, name="batch_edit"),
    path("batches/<int:pk>/assign/", views.batch_assign_reviewers, name="batch_assign_reviewers"),
    path("queue/", views.applicant_queue, name="applicant_queue"),
    path('<int:pk>/toggle-flag/', toggle_applicant_flag, name='toggle_applicant_flag'),
    path("bulk-upload/", views.bulk_upload_applicants, name="bulk_upload"),
    path("datasets/<int:pk>/archive/", views.dataset_archive, name="dataset_archive"),
    path("committee/dashboard/", views.committee_dashboard, name="committee_dashboard"),
    path("committee/reviews/", views.my_reviews, name="my_reviews"),
    path("committee/activity/", views.my_activity, name="my_activity"),
    path("batches/bulk-action/", views.batch_bulk_action, name="batch_bulk_action"),
    ]
